#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
One-click publish for XinghuisamaBlogs.

What it does:
  1. Mirror console data (my-blog-manager) into XHBlogs.
  2. git add ONLY the content directories, commit, and push to origin/main.
  3. Vercel rebuilds automatically after the push.

Usage:
  python publish.py

Notes:
  - This script publishes CONTENT only. It does NOT touch code/config files.
  - siteConfig.ts is copied with image-bed tokens stripped (never pushed to GitHub).
  - SSH: prefers ~/.ssh/id_ed25519_source (generated by the console), falls back to default key.
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MGR = os.path.join(ROOT, "manager")
XH = ROOT  # blog is at repo root after restructuring

SYNC_DIRS = ["posts", "chatters", "moments"]
SYNC_FILES = [
    "app/about/about.md",
    "data/albums.ts",
    "data/friends.ts",
    "data/projects.ts",
    "siteConfig.ts",
]

# Keywords whose lines are stripped from siteConfig.ts before pushing (sensitive).
SITE_CONFIG_SKIP = ("picBedName:", "picBedUrl:", "picBedToken:", "图床核心配置")


def sync_tree(src, dst):
    """Mirror src -> dst file-by-file (no rmtree, sandbox-safe)."""
    if not os.path.exists(src):
        return
    os.makedirs(dst, exist_ok=True)
    src_files = set()
    for root, _dirs, files in os.walk(src):
        rel = os.path.relpath(root, src)
        tgt = dst if rel == "." else os.path.join(dst, rel)
        os.makedirs(tgt, exist_ok=True)
        for name in files:
            s = os.path.join(root, name)
            d = os.path.join(tgt, name)
            shutil.copy2(s, d)
            src_files.add(os.path.relpath(d, dst))
    # Clean files in dst that no longer exist in src (ignore failures in restricted envs).
    for root, _dirs, files in os.walk(dst):
        for name in files:
            f = os.path.join(root, name)
            if os.path.relpath(f, dst) not in src_files:
                try:
                    os.remove(f)
                except Exception:
                    pass


def copy_file(src, dst, strip_siteconfig=False):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if strip_siteconfig:
        with open(src, "r", encoding="utf-8") as fin:
            lines = fin.readlines()
        with open(dst, "w", encoding="utf-8") as fout:
            for line in lines:
                if any(k in line for k in SITE_CONFIG_SKIP):
                    continue
                fout.write(line)
    else:
        shutil.copy2(src, dst)


def run(cmd, env=None, cwd=None):
    print(">>", cmd if isinstance(cmd, str) else " ".join(cmd))
    r = subprocess.run(
        cmd,
        shell=isinstance(cmd, str),
        env=env,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if r.stdout:
        print(r.stdout)
    if r.stderr:
        print(r.stderr)
    return r


def ensure_gitignore():
    """Make sure .workbuddy/ and venv are ignored so they never get committed."""
    path = os.path.join(ROOT, ".gitignore")
    existing = ""
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
    needed = [".workbuddy/", "manager/.venv/"]
    add = [n for n in needed if n not in existing]
    if add:
        with open(path, "a", encoding="utf-8") as f:
            f.write("\n" + "\n".join(add) + "\n")
        print("Updated .gitignore with:", add)


def main():
    print("=== Step 1: mirror console data -> blog (root) ===")
    for d in SYNC_DIRS:
        sync_tree(os.path.join(MGR, d), os.path.join(XH, d))
    for f in SYNC_FILES:
        s = os.path.join(MGR, f)
        if os.path.exists(s):
            copy_file(s, os.path.join(XH, f), strip_siteconfig=(f == "siteConfig.ts"))
    print("Mirror done.\n")

    print("=== Step 2: git add content + commit + push ===")
    ensure_gitignore()

    os.chdir(ROOT)
    content_paths = SYNC_DIRS + SYNC_FILES
    run(["git", "add"] + content_paths)

    # Commit (tolerate "nothing to commit").
    run(['git commit -m "Auto publish content via one-click script" || echo NO_CHANGES'], cwd=ROOT)

    # Push: prefer the console-generated source key, else default SSH key.
    ssh_dir = os.path.expanduser("~/.ssh")
    priv = os.path.join(ssh_dir, "id_ed25519_source")
    env = os.environ.copy()
    if os.path.exists(priv):
        env["GIT_SSH_COMMAND"] = f'ssh -i "{priv}" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'
        print("Using id_ed25519_source key for push.")
    else:
        print("Using default SSH key for push.")

    p = run('git push origin HEAD:main', env=env, cwd=ROOT)
    if p.returncode == 0 or (p.stderr and "Everything up-to-date" in p.stderr):
        print("\n[OK] Pushed. Vercel will rebuild shortly.")
    else:
        print("\n[FAIL] Push failed. Check that your GitHub fork has a writable SSH key/deploy key.")
        sys.exit(1)


if __name__ == "__main__":
    main()
